export const FilmData = {
  backgroundImg: 'img/bg-the-grand-budapest-hotel.jpg',
  backgroundImgAlt: 'The Grand Budapest Hotel',
  poster: 'img/the-grand-budapest-hotel-poster.jpg',
  altPoster:'The Grand Budapest Hotel poster',
  title: 'The Grand Budapest Hotel',
  genre: 'Drama',
  year: 2014,
  urlMovie: 'film-page.html',
  ratingAbsolute: '8,9',
  ratingRelative: 'Very good',
  ratingCount: 240,
  description: `In the 1930s, the Grand Budapest Hotel is a popular European ski resort, presided over by concierge Gustave H. (Ralph Fiennes). Zero, a junior lobby boy, becomes Gustave's friend and protege. ${<br/>} Gustave prides himself on providing first-class service to the hotel's guests, including satisfying the sexual needs of the many elderly women who stay there. When one of Gustave's lovers dies mysteriously, Gustave finds himself the recipient of a priceless painting and the chief suspect in her murder.`,
  director: 'Wes Anderson',
  actors: 'Bill Murray, Edward Norton, Jude Law, Willem Dafoe',
  privateInfoWeb: {
    isInMyList: false,
    hasAddReview: false,
    isGenreActive: false,
    isLogged: true,
  },
};
